export const SET_SINGER = 'SET_SINGER'

export const SET_PLAYING_STATE = 'SET_PLAYING_STAT'

export const SET_FULL_SCREEN_STATE = 'SET_FULL_SCREEN_STATE'

export const SET_PLAY_LIST_STATE = 'SET_PLAY_LIST_STATE'

export const SET_SEQUENCE_LIST_STATE = 'SET_SEQUENCE_LIST_STATE'

export const SET_PLAY_MODE_STATE = 'SET_PLAY_MODE_STATE'

export const SET_CURRENT_INDEX_STATE = 'SET_CURRENT_INDEX_STATE'
